name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: node:lts
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build Project
        run: npm build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: html
          path: dist/